# Add these steps after your Flask import check:
    
    - name: Run Flake8 Linting
      run: |
        echo "Running code linting..."
        flake8 . --count --statistics --show-source
      continue-on-error: true
    
    - name: Check code formatting with Black
      run: |
        echo "Checking code formatting..."
        black --check --diff .
      continue-on-error: true
    
    - name: Run security checks
      run: |
        echo "Running security scans..."
        safety check
        bandit -r . -f json -o bandit-report.json
      continue-on-error: true
    
    - name: Run Unit Tests
      run: |
        echo "Running unit tests..."
        if [ -f "tests/test_app.py" ]; then
          pytest tests/test_app.py -v --tb=short
        else
          echo "Unit test file not found - creating basic structure"
          mkdir -p tests
          touch tests/__init__.py
        fi
      env:
        FLASK_ENV: testing
    
    - name: Run Integration Tests
      run: |
        echo "Running integration tests..."
        if [ -d "tests/integration" ]; then
          pytest tests/integration/ -v --tb=short
        else
          echo "Integration tests not found - skipping"
        fi
      env:
        FLASK_ENV: testing
    
    - name: Generate test coverage
      run: |
        echo "Generating test coverage report..."
        if [ -d "tests" ] && [ "$(find tests -name '*.py' -not -name '__init__.py' | wc -l)" -gt 0 ]; then
          pytest --cov=. --cov-report=term-missing --cov-report=html
        else
          echo "No tests found - skipping coverage"
        fi
      continue-on-error: true
    
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: htmlcov/
      if: always()
    
    - name: Final CI Summary
      run: |
        echo "================================"
        echo "CI Pipeline Execution Summary:"
        echo "✓ Dependencies installed"
        echo "✓ Flask app validated"
        echo "✓ Code quality checks completed"
        echo "✓ Security scans executed"
        echo "✓ Tests attempted"
        echo "================================"